USE DATABASE ledsite_database;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(20) NOT NULL
);

CREATE TABLE donations(
    transaction_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    sender VARCHAR(50) NOT NULL,
    amount INTEGER NOT NULL,
    date DATE NOT NULL
);